### ISSUE TITLE
Change XDG defaults on Windows to use Windows spec

### ISSUE THREAD

**Issue by kirawi** [lunacookies/etcetera#18]
Ref https://github.com/helix-editor/helix/issues/6747

When the environment variables aren't set, they should use the Windows location instead. This is how most XDG implementations handle fallback on Windows, such as [glib](https://docs.gtk.org/glib/func.get_user_config_dir.html).

**Comment by kirawi** [comment]
I'm not sure what would be the preferred solution, so I'll ask the other maintainers.

**Comment by utkarshgupta137** [comment]
I think I would prefer making that function public so it is easier for all devs to mix & match strategies as they require. `XdgWindows` or `XdgApple` would just be a special case of that function.
In case you weren't aware, you could also implement the traits for your own struct & use that everywhere. It is especially helpful if you're changing the default paths & want a fallback solution in a single place in your workspace.
I'm also interested in using Helix, so let me know in case you need any help with https://github.com/helix-editor/helix/pull/2135 or similar functionality.

**Comment by kirawi** [comment]
After speaking with one of the maintainers, your suggestion would work for Helix.

**Comment by utkarshgupta137** [comment]
Would you be fine with copying [this function](https://github.com/lunacookies/etcetera/blob/master/src/base_strategy/xdg.rs#L160-L171) or do you really really want it to be in this library? From my perspective, this function actually doesn't have anything to do with this crate & one could pass any unrelated variables to it.

**Comment by kirawi** [comment]
Yep we can copy this function.

**Comment by refack** [comment]
@utkarshgupta137 how about the opposite, make the Windows strategies check the existence of `XGD_*` env vars, and if they exist they take priority?

P.S. if you think it's a good idea, I'd be happy to write a PR.

**Comment by utkarshgupta137** [comment]
> [@utkarshgupta137](https://github.com/utkarshgupta137) how about the opposite, make the Windows strategies check the existence of `XGD_*` env vars, and if they exist they take priority?
> 
> P.S. if you think it's a good idea, I'd be happy to write a PR.

Could you not just use base_strategy::Xdg directly in that case?

**Comment by refack** [comment]
1. I was thinking about making it a "just work" for all the projects that depend on `etcetera`
2. Since the existence of `XDG_*` env vars in abstracted away nicely, the consumer has no way of knowing is they are getting a user value or the default. So they'll need some env checking logic to decide which strategy to use...
 
* On WINNT `APPDATA` and `LOCALAPPDATA` should always exist, but setting up `XDG_CACHE_HOME` and `XDG_CONFIG_HOME` is an explicit act by the user or admin.
* Several platform portable tools already respect the XDG schema on Windows

**Comment by utkarshgupta137** [comment]
> 1. I was thinking about making it a "just work" for all the projects that depend on `etcetera`
> 
>     2. Since the existence of `XDG_*` env vars in abstracted away nicely, the consumer has no way of knowing is they are getting a user value or the default. So they'll need some env checking logic to decide which strategy to use...
> 
> 
>     * On WINNT `APPDATA` and `LOCALAPPDATA` should always exist, but setting up `XDG_CACHE_HOME` and `XDG_CONFIG_HOME` is an explicit act by the user or admin.
> 
>     * Several platform portable tools already respect the XDG schema on Windows

I don't use Windows, so I don't really have strong opinions, but what you're suggesting is an anti-pattern. You either follow XDG or you don't. Following XDG means respecting XDG variables & falling back to `~/.config` & `~/.local/share` etc. if those variables aren't defined.
For the vast majority of people like me who set XDG variables to the default values, it is really annoying when you run a script or a launchd service without the XDG variables to suddenly start behaving differently. Yes, this doesn't have anything to do with Windows & the same issue exists on Linux if you don't use "standard paths" for $XDG, but that is probably a very small subset of users.
I do know of a few tools as a macOS user which fallback to `~/Library` paths which are meant for GUI apps (lots of go programs do this) & it is always frustrating to discover. But if this is a common pattern for CLIs on Windows, then I can consider adding it.

**Comment by refack** [comment]
I'm a "Windows First" dummy, but I want to facilitate the opt-in cross-platform flow.
The pattern I'm suggesting I "stole" from other tools that do the same, i.e.
1. Do the silly M$ default dance, if nothing else is defined (%USERPROFILE%\[Local]AppData wishwash)
2. Do the slightly smarter flow, if XDG_* environment variables are defined
3. Do the VERY EXPLICIT `<APP>_CACHE/DATA/CONFIG_DIR` if the user really wants that.

I'm talking about tools like `astral-sh/uv` which is taking over the Python ecosystem by storm (with the magic of rust) https://github.com/nodejs/node/issues/59334

**Comment by utkarshgupta137** [comment]
> I'm a "Windows First" dummy, but I want to facilitate the opt-in cross-platform flow.
> The pattern I'm suggesting I "stole" from other tools that do the same, i.e.
> 1. Do the silly M$ default dance, if nothing else is defined (%USERPROFILE%\[Local]AppData wishwash)
> 2. Do the slightly smarter flow, if XDG_* environment variables are defined
> 3. Do the VERY EXPLICIT `<APP>_CACHE/DATA/CONFIG_DIR` if the user really wants that.
> 
> I'm talking about tools like `astral-sh/uv` which is taking over the Python ecosystem by storm (with the magic of rust) https://github.com/nodejs/node/issues/59334

I don't think uv supports XDG on Windows. It is just using etcetera for config/cache/data etc. It only seems to be using XDG_BIN_HOME on Windows.
If this is a common pattern (or a common desired pattern) for Rust tools on Windows, then I willing to add it in etcetera as long as it is explicit that it is an anti-pattern & not recommended.
